# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 137f69511f53791736b835a8843f4368dc31227f7a4e08ea8787bcc521c9cefe4f3b6cc9d7854e6b730c45bd2361922199193408fce217595173cf36d6897013
  FACEBOOK_APP_ID: 178589242485708
  FACEBOOK_SECRET: bd9d4273ea5b10af538b681356c470b6
  GOOGLE_CLIENT_ID: "578074026093-i1ls0a4coo0gf4rr6aer7v7gp1k4uftj.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "WPcLvEzxoo5xgROtWWeCZ0EE"

test:
  secret_key_base: 480dd0dea2f7365bd3ff3ff0418efd0b9adfe6d8d8bf32c10ff6b76d0294a2852822b0995051260a4bc77a6a0a8a54dad1d311ce50ab5b81a618a7b622d033dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FACEBOOK_APP_ID: <%= ENV["FACEBOOK_APP_ID"] %>
  FACEBOOK_SECRET: <%= ENV["FACEBOOK_SECRET"] %>
  GOOGLE_CLIENT_ID: <%= ENV["GOOGLE_CLIENT_ID"] %>
  GOOGLE_CLIENT_SECRET: <%= ENV["GOOGLE_CLIENT_SECRET"] %>